/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JFileChooser;

/**
 *
 * @author David
 */
public class Screen extends javax.swing.JFrame {

    CapturadorAudio cp_audio;

    /**
     * Función que reproduce un archivo de audio tipo wav.
     *
     * Abre el archivo como entrada de audio y lo reproduce con la interfaz
     * clip, que es la que tiene los métodos necesarios para ello.
     *
     * @param name Ubicación del archivo
     */
    private void playwav(String name) {
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(name).getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
            while (!clip.isRunning()) {
                Thread.sleep(10);
            }
            while (clip.isRunning()) {
                Thread.sleep(10);
            }
            clip.close();
        } catch (Exception ex) {
            System.out.println("Error with playing sound.");
            ex.printStackTrace();
        }
    }

    /**
     * Inicia la grabación de audio.
     *
     * @param calidad Calidad con la que se va a grabar.
     */
    private void iniciar(int calidad) {
        cp_audio.capturaAudio(calidad);
    }

    /**
     * Función que se ejecuta al finalizar la aplicación.
     *
     * Se encarga de finalizar correctamente el programa.
     */
    private void finAplicacion() {
        int respuesta;
        respuesta = javax.swing.JOptionPane.showConfirmDialog(rootPane,
                "¿Realmente desea salir?",
                "Salir de la aplicación",
                javax.swing.JOptionPane.OK_CANCEL_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (respuesta == javax.swing.JOptionPane.OK_OPTION) {
            this.setVisible(false);
            this.dispose();

            //Se borra el archivo temporal
            File tmp = new File("tmp.wav");
            tmp.delete();
        }
    }

    /**
     * Procedimiento que guarda el archivo.
     * 
     * Para ello, coge el archivo origen temporal que genera el programa y lo
     * copia en la nueva ubicación elegida. Además no es necesario añadir la
     * terminación ".wav" ya que el procedimiento se encarga de añadirla antes
     * de guardar el archivo.
     * 
     * En caso de no elegir ubicación, no se guarda el archivo.
     */
    private void guardar() {
        File tmp = new File("tmp.wav");
        File nuevo;
        int returnVal = chooser.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            nuevo = chooser.getSelectedFile();
            //Se añade la terminación .wav al archivo
            File def = new File(nuevo.getPath() + ".wav");
            try {
                Files.copy(tmp.toPath(), def.toPath());
            } catch (IOException ex) {
                Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Incorrecto");
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No se ha podido guardar.",
                        "Mensaje",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            System.out.println("No se ha guardado el archivo");
        }
    }

    /**
     * Creates new form screen
     */
    public Screen() {
        initComponents();
        // m = new Repro();
        cp_audio = new CapturadorAudio();
        btstart.setEnabled(true);
        btplay.setEnabled(false);
        btstop.setEnabled(false);
        btsave.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooser = new javax.swing.JFileChooser();
        btstart = new javax.swing.JButton();
        btstop = new javax.swing.JButton();
        btplay = new javax.swing.JButton();
        btsave = new javax.swing.JButton();
        btsalir = new javax.swing.JButton();
        cbcalidad = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        menuGraba = new javax.swing.JMenuItem();
        menuGuarda = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenuItem();
        MenuAyuda = new javax.swing.JMenu();
        ItAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grabar audio");

        btstart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Button-Rec-icon.png"))); // NOI18N
        btstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btstartActionPerformed(evt);
            }
        });

        btstop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/sutop.png"))); // NOI18N
        btstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btstopActionPerformed(evt);
            }
        });

        btplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/playb.png"))); // NOI18N
        btplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btplayActionPerformed(evt);
            }
        });

        btsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/save.png"))); // NOI18N
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });

        btsalir.setText("Salir");
        btsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalirActionPerformed(evt);
            }
        });

        cbcalidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Conversacion", "Radio FM", "CD Audio" }));

        jLabel1.setText("Calidad del audio:");

        MenuArchivo.setText("Archivo");

        menuGraba.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuGraba.setText("Iniciar grabación");
        menuGraba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGrabaActionPerformed(evt);
            }
        });
        MenuArchivo.add(menuGraba);

        menuGuarda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        menuGuarda.setText("Guardar...");
        menuGuarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGuardaActionPerformed(evt);
            }
        });
        MenuArchivo.add(menuGuarda);

        MenuSalir.setText("Salir");
        MenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirActionPerformed(evt);
            }
        });
        MenuArchivo.add(MenuSalir);

        jMenuBar1.add(MenuArchivo);

        MenuAyuda.setText("Ayuda");

        ItAcerca.setText("Acerca de");
        ItAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItAcercaActionPerformed(evt);
            }
        });
        MenuAyuda.add(ItAcerca);

        jMenuBar1.add(MenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(cbcalidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btstart, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btstop, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btplay, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btsave, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbcalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btsave)
                        .addComponent(btplay, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btstop, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btstart))
                .addGap(35, 35, 35)
                .addComponent(btsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btstartActionPerformed
        btplay.setEnabled(false);
        btstop.setEnabled(true);
        btstart.setEnabled(false);
        menuGraba.setEnabled(false);

        Object opcion = cbcalidad.getSelectedItem();
        String calidad = opcion.toString();
        switch (calidad) {
            case "Conversacion":
                iniciar(0);
                break;
            case "Radio FM":
                iniciar(1);
                break;
            default:
                iniciar(2);
                break;
        }
    }//GEN-LAST:event_btstartActionPerformed

    private void btstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btstopActionPerformed
        cp_audio.paraCaptura();
        btplay.setEnabled(true);
        btstop.setEnabled(false);
        btstart.setEnabled(true);
        menuGraba.setEnabled(true);
        btsave.setEnabled(true);
    }//GEN-LAST:event_btstopActionPerformed

    private void btplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btplayActionPerformed
        btplay.setEnabled(true);
        btstop.setEnabled(false);
        btstart.setEnabled(true);
        menuGraba.setEnabled(true);
        playwav("tmp.wav");
    }//GEN-LAST:event_btplayActionPerformed

    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed
        guardar();
        btplay.setEnabled(false);
        btstop.setEnabled(false);
        btstart.setEnabled(true);
        menuGraba.setEnabled(true);
    }//GEN-LAST:event_btsaveActionPerformed

    private void ItAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItAcercaActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,
                "(c) David Abad Vich\n"
                + "Sistemas Multimedia\n"
                + "2013",
                "Acerca de...",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ItAcercaActionPerformed

    private void btsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalirActionPerformed
        finAplicacion();
    }//GEN-LAST:event_btsalirActionPerformed

    private void MenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirActionPerformed
        finAplicacion();
    }//GEN-LAST:event_MenuSalirActionPerformed

    private void menuGrabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGrabaActionPerformed
        menuGraba.setEnabled(false);
        btplay.setEnabled(false);
        btstop.setEnabled(true);
        btstart.setEnabled(false);
        Object opcion = cbcalidad.getSelectedItem();
        String calidad = opcion.toString();
        switch (calidad) {
            case "Conversacion":
                iniciar(0);
                break;
            case "Radio FM":
                iniciar(1);
                break;
            default:
                iniciar(2);
                break;
        }
    }//GEN-LAST:event_menuGrabaActionPerformed

    private void menuGuardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuardaActionPerformed
        guardar();
        btplay.setEnabled(false);
        btstop.setEnabled(false);
        btstart.setEnabled(true);
        menuGraba.setEnabled(true);
    }//GEN-LAST:event_menuGuardaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Screen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItAcerca;
    private javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenu MenuAyuda;
    private javax.swing.JMenuItem MenuSalir;
    private javax.swing.JButton btplay;
    private javax.swing.JButton btsalir;
    private javax.swing.JButton btsave;
    private javax.swing.JButton btstart;
    private javax.swing.JButton btstop;
    private javax.swing.JComboBox cbcalidad;
    private javax.swing.JFileChooser chooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuGraba;
    private javax.swing.JMenuItem menuGuarda;
    // End of variables declaration//GEN-END:variables
}
